name: Python Application

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Tests
      run: |
        mkdir -p output
        python3 find_lowest_number.py test_data/test1_input.txt output/test1_output.txt
        python3 find_lowest_number.py test_data/test2_input.txt output/test2_output.txt
        python3 find_lowest_number.py test_data/test3_input.txt output/test3_output.txt
        diff output/test1_output.txt test_data/test1_expected.txt
        diff output/test2_output.txt test_data/test2_expected.txt
        diff output/test3_output.txt test_data/test3_expected.txt
